ACM_Registration_Portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls', namespace='MainApp')),
]

MainApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'MainApp'

urlpatterns = [
    path('', home, name='home'),
    path('login/', loginPage, name='login'),
    path('event/', event, name='event'),
    path('logout/',logoutPage,name='logout'),
    path('signin/',signin,name='signin'),
    path('register/',register,name='register'),
    path('about/',about,name='about'),
    path('account/',account,name='account'),
    path('account/updatePassword/<int:id>',updatePassword,name='updatePassword'),
    path('recovery/',recovery,name='recovery'),
    path('sendpassword/',sendpassword,name='sendpassword'),
    path('registration/',registration,name='registration'),
    path('createteam/',createteam,name='createteam'),
    path('checkteam/',checkteam,name='checkteam'),
    path('deleteteam/<str:team_name>',deleteteam,name='deleteteam'),
    path('problems/',problems,name='problems'),
    path('getteams/',getteams,name='getteams'),
    path('info/',info,name='info')
]

MainApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    USN = models.CharField(max_length=10)
    USERNAME_FIELD = "email"
    is_registered=models.BooleanField(default=False)
    year=models.CharField(max_length=4,default='2025')
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Team(models.Model):
    team_name = models.CharField(max_length=100, primary_key=True)
    team_leader = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    team_member1 = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='team_member1', null=True, blank=True)
    team_member2 = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='team_member2', null=True, blank=True)
    team_member3 = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='team_member3', null=True, blank=True)
    problem_no = models.IntegerField(default=1, validators=[MaxValueValidator(25), MinValueValidator(1)])

    def __str__(self):
        return self.team_name

MainApp/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect,get_object_or_404
from django.contrib.auth import authenticate, login,logout
from .models import *
import random
from django.core.mail import send_mail
from django.contrib import messages
from ACM_Registration_Portal.settings import EMAIL_HOST_USER
import random
import string
from django.conf import settings
import os
import csv



def generate_random_password(length):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

# Create your views here.
def home(request):
    # send_mail(
    #     'Subject here',
    #     'Here is the message.',
    #     EMAIL_HOST_USER,
    #     ['shubhammirashi303@gmail.com'],
    #     fail_silently=False,
    # )
    return render(request,'MainApp/home.html')

def loginPage(request):
    return render(request,'MainApp/login.html')

def event(request):
    return render(request,'MainApp/event.html')

def logoutPage(request):
    logout(request)
    return home(request)

def signin(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email,password)
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request,user)
            print("success")
            return JsonResponse({'data':'success'})
        else:
            return HttpResponse(status=401)
    return HttpResponse(status=404)

def register(request):
    if request.method == 'POST':
        email = request.POST['email']
        USN=request.POST['USN']
        name=request.POST['name']
        year=request.POST['year']
        print(email,USN,name,year)
        password = generate_random_password(6)
        if CustomUser.objects.filter(email=email).exists():
            val=CustomUser.objects.get(email=email)
            val.set_password(password)
        else:
            print("he must login")
            val=CustomUser(email=email,USN=USN,first_name=name,year=year)
            val.set_password(password)
        send_mail(
            'Credentials for ACM Nexus',
            "Your username is "+email+"\n"+'Your password is '+password,
            EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        val.save()
        return render(request,'MainApp/confirmation.html')
    return HttpResponse(status=404)

def about(request):
    if request.method == "POST":
        first_name = request.POST.get("first-name")
        last_name = request.POST.get("last-name")
        email = request.POST.get("email")
        message = request.POST.get("message")

        subject = f"Contact Form Submission from {first_name} {last_name}"
        body = f"Name: {first_name} {last_name}\nEmail: {email}\n\nMessage:\n{message}"

        recipient_email = "22u1428@students.git.edu"  

        try:
            send_mail(subject, body, email, [recipient_email])
            messages.success(request, "Your message has been sent successfully!")
        except Exception as e:
            messages.error(request, f"Failed to send message: {str(e)}")

        return redirect("/about/")  

    return render(request,'MainApp/about.html')



def account(request):
    return render(request,'MainApp/account.html')

def updatePassword(request,id):
    if request.method=='POST':
        user = CustomUser.objects.get(id=id)
        # print(user)
        # print(request.POST['password'])
        user.set_password(request.POST.get('password'))
        user.save()
        return HttpResponseRedirect('/account')
    return HttpResponse(status=404)

def recovery(request):
    return render(request,'MainApp/recovery.html')

def sendpassword(request):
    if request.method=='POST':
        email=request.POST['email']
        if CustomUser.objects.filter(email=email).exists():
            user=CustomUser.objects.get(email=email)
            password=generate_random_password(6)
            user.set_password(password)
            send_mail(
                'Credentials for ACM Nexus',
                "Your username is "+email+"\n"+'Your password is '+password,
                EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )
            user.save()
            return render(request,'MainApp/confirmation.html')
        return render(request,'MainApp/confirmation.html')
    return HttpResponse(status=404)

def registration(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login')
    elif Team.objects.filter(team_leader=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_leader=request.user)})
    elif Team.objects.filter(team_member1=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member1=request.user)})
    elif Team.objects.filter(team_member2=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member2=request.user)})
    elif Team.objects.filter(team_member3=request.user).exists():
        return render(request,'MainApp/registered.html',context={'team':Team.objects.get(team_member3=request.user)})
    return render(request,'MainApp/registration.html')

def createteam(request):
    if request.method=='POST':
        team_name=request.POST['name']
        if Team.objects.filter(team_name=team_name).exists():
            return HttpResponse(status=404)
        else:
            return render(request,'MainApp/registration.html')
    return HttpResponse(status=404)

def checkteam(request):
    if request.method == 'POST':
        team_name = request.POST['name']
        team_leader = request.POST['email1']
        team_member1 = request.POST['email2']
        team_member2 = request.POST.get('email3')  
        team_member3 = request.POST.get('email4') 
        problem_number = request.POST.get('problem')

       
        if Team.objects.filter(team_name=team_name).exists():
            return HttpResponse(status=404, reason='Team Name already exists\nTry with a different name')

        
        if problem_number not in [str(i) for i in range(1, 26)]:
            return HttpResponse(status=404, reason='Problem Number is not valid')

      
        if not CustomUser.objects.filter(email=team_member1).exists():
            return HttpResponse(status=404, reason='Team Member 2 does not exist')

        if team_member2 and not CustomUser.objects.filter(email=team_member2).exists():
            return HttpResponse(status=404, reason='Team Member 3 does not exist')

        if team_member3 and not CustomUser.objects.filter(email=team_member3).exists():
            return HttpResponse(status=404, reason='Team Member 4 does not exist')

      
        if Team.objects.filter(team_member1=CustomUser.objects.get(email=team_member1)).exists():
            return HttpResponse(status=404, reason='Team Member 2 already has a team')

        if team_member2 and Team.objects.filter(team_member2=CustomUser.objects.get(email=team_member2)).exists():
            return HttpResponse(status=404, reason='Team Member 3 already has a team')

        if team_member3 and Team.objects.filter(team_member3=CustomUser.objects.get(email=team_member3)).exists():
            return HttpResponse(status=404, reason='Team Member 4 already has a team')

        
        leader = CustomUser.objects.get(email=team_leader)
        member1 = CustomUser.objects.get(email=team_member1)
        leader.is_registered = True
        member1.is_registered = True

        if team_member2:
            member2 = CustomUser.objects.get(email=team_member2)
            member2.is_registered = True
        else:
            member2 = None

        if team_member3:
            member3 = CustomUser.objects.get(email=team_member3)
            member3.is_registered = True
        else:
            member3 = None

        val = Team(
            team_name=team_name,
            team_leader=leader,
            team_member1=member1,
            team_member2=member2,
            team_member3=member3,
            problem_no=problem_number
        )
        val.save()
        leader.save()
        member1.save()
        if member2:
            member2.save()
        if member3:
            member3.save()

        return JsonResponse({'data': 'success'})

    return HttpResponse(status=404)


def deleteteam(request, team_name):
    if request.method == 'POST':
        team = get_object_or_404(Team, team_name=team_name) 
        
        if team.team_leader:
            team.team_leader.is_registered = False
            team.team_leader.save()
        
        if team.team_member1:
            team.team_member1.is_registered = False
            team.team_member1.save()
        
        if team.team_member2:
            team.team_member2.is_registered = False
            team.team_member2.save()
        
        if team.team_member3:
            team.team_member3.is_registered = False
            team.team_member3.save()

        team.delete()
        return HttpResponseRedirect('/account')

    return HttpResponse(status=404)

def problems(request):
    f = open(os.path.join(settings.STATIC_ROOT, 'data/data.csv'), 'r')
    reader = csv.reader(f)
    next(reader)
    data_list = list(reader)

    s = {}
    theme = {}
    no = 1
    count = 1
    val = "IOT"

    for a in data_list:
        if val == a[1]:
            if count not in s:
                s[count] = []
            s[count].append((no, a[0]))
            no += 1
        else:
            theme[count] = val
            count += 1
            val = a[1]

            if count not in s:
                s[count] = []
            s[count].append((no, a[0]))
            no += 1

    theme[count] = val

    f.close()

MainApp/templates/MainApp/about.html
{% extends 'base.html' %} {% load static %} {% block head %}
<title>About</title>
<link rel="stylesheet" href="{% static 'MainApp/about.css'%}" />
<style>
  swiper-container {
    width: 100%;
    padding-top: 50px;
    padding-bottom: 50px;
  }

  swiper-slide {
    background-position: center;
    background-size: cover;
    width: 300px;
    height: 300px;
  }

  swiper-slide img {
    display: block;
    width: 100%;
  }
</style>
{% endblock head %} {% block body %}
<body>
  <div class="header">
    <div>
      <h1>ACM NEXUS 2.0</h1>
      <p>About us</p>
    </div>
  </div>

  <div class="content">
    <div class="side-text">INCEPTION</div>

    <div class="info-section">
      <h2>ACM Nexus</h2>
      <p>
        ACM Nexus is an intense 24-hour hackathon where innovative minds come together to tackle real-world challenges through technology. Participants collaborate, code, and create impactful solutions to some of society’s most pressing issues. This event is not just a competition—it’s a platform for students to showcase their creativity, problem-solving skills, and technical expertise while making a meaningful difference.
      </p>
    </div>

    <div class="image-placeholder">
      <img src="{% static 'Images/thinking.png' %}" alt="" />
    </div>
  </div>

  <div class="content">
    <div class="info-section">
      <h2>TRADITIONS</h2>
      <p>
        Nexus has grown into a dynamic hub for inquisitive minds to collaborate, innovate, and push the boundaries of technology. What started as an initiative to bring together brilliant thinkers has now become an annual tradition, fostering creativity and problem-solving on a grand scale. Each edition introduces fresh challenges and opportunities, inspiring participants to explore new frontiers in science, technology, and societal impact.
      </p>
    </div>
    <div class="sliderpics"></div>
    <div class="image-placeholder">
      <img src="{% static 'Images/group.png' %}" alt="" />
    </div>
  </div>

  <div class="swiper-section" style="width: 100%;">
    <swiper-container
      class="mySwiper"
      pagination="true"
      effect="coverflow"
      grab-cursor="true"
      centered-slides="true"
      slides-per-view="auto"
      coverflow-effect-rotate="50"
      coverflow-effect-stretch="0"
      coverflow-effect-depth="100"
      coverflow-effect-modifier="1"
      coverflow-effect-slide-shadows="true"
      autoplay-delay="2500"
      autoplay-disable-on-interaction="false">
      <swiper-slide>
        <img src="{% static 'Images/people.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/empower-ED.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/cipherConquest.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/posterverse.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/something.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/fiesta.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/hack.jpg' %}" alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src="{% static 'Images/git.jpg' %}" alt="" />
      </swiper-slide>
 
  </div>

  <div id="contact-US">
    <div class="contact-section">
      <div class="contact-info">
        <h1>Contact Us</h1>
        <p><strong>Phone</strong></p>
        <p>
          Coordinators:<br />
          7259544987 <br />
          9420689497
        </p>
        <p>
          PR Team:<br />
          8105193555 <br />
          6362990994
        </p>

        <p><strong>Email</strong></p> 
        <p>
          <a href="mailto:22u1428@students.git.edu"> ACM KLS GIT </a>
        </p>

        <p><strong>Address :</strong></p>
        <p>
          KLS GIT Belgaum<br />
          Udyambag Industrial Area, Udyambag,<br />
          Belagavi, Karnataka ,<br />
          India – 590006.
        </p>
      </div>

      <div class="contact-form">
        <form action="{% url 'MainApp:about' %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <input type="text" name="first-name" placeholder="First Name" required />
            <input type="text" name="last-name" placeholder="Last Name" required />
          </div>
          <input type="email" name="email" placeholder="Email *" required />
          <textarea name="message" rows="5" placeholder="Message" required></textarea>
          <button type="submit" class="send-btn">Send</button>
        </form>
      </div>
      
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}


  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
  <canvas id="nexusCanvas"></canvas>
<script >
    const canvas = document.getElementById('nexusCanvas');
const ctx = canvas.getContext('2d');

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let particles = [];
const particleCount = 100;

class Particle {
    constructor() {
        this.x = Math.random() * canvas.width;
        this.y = Math.random() * canvas.height;
        this.size = Math.random() * 3 + 1;
        this.speedX = (Math.random() - 0.5) * 0.3;
        this.speedY = (Math.random() - 0.5) * 0.3;
        this.color = `rgba(173, 216, 230, 0.5)`;
    }

    update() {
        this.x += this.speedX;
        this.y += this.speedY;

        if (this.x > canvas.width || this.x < 0) this.speedX *= -1;
        if (this.y > canvas.height || this.y < 0) this.speedY *= -1;
    }

    draw() {
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
        ctx.fillStyle = this.color;
        ctx.fill();
    }
}

function createParticles() {
    particles = [];
    for (let i = 0; i < particleCount; i++) {
        particles.push(new Particle());
    }
}

function drawConnections() {
    for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
            let dx = particles[i].x - particles[j].x;
            let dy = particles[i].y - particles[j].y;
            let distance = Math.sqrt(dx * dx + dy * dy);

            if (distance < 120) {
                ctx.beginPath();
                ctx.strokeStyle = `rgba(173, 216, 230, ${1 - distance / 120})`;
                ctx.lineWidth = 0.5;
                ctx.moveTo(particles[i].x, particles[i].y);
                ctx.lineTo(particles[j].x, particles[j].y);
                ctx.stroke();
            }
        }
    }
}

function animate() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    particles.forEach(particle => {
        particle.update();
        particle.draw();
    });

    drawConnections();
    requestAnimationFrame(animate);
}

window.addEventListener('resize', () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    createParticles();
});

createParticles();
animate();

</script>
  {% endblock body %}
</body>

MainApp/templates/MainApp/account.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/account.css' %}">
{% endblock head %}
{% block body %}
<form action="updatePassword/{{user.id}}" method="post" class="block" id="block" onsubmit="return validateForm()">
    <div class="inner-block">
        {% csrf_token %}
        <h1>Change Password</h1>
        <input type="text" id="password" name="password" class="pass" placeholder="Password" required>
        <input type="password" id="password2"  class="pass" placeholder="Re-Enter Password" required>
        <div class="button">
            <div class="cancel" onclick="closeBlock()">Cancel</div>
            <input class="submit" type="submit" value="Submit">
        </div>
    </div>
</form>
    <div id="content">
        <h1>Welcome {{user.first_name}}!!!!!</h1>
        <hr>
        <div class="conatiner-account">
        <div class="deatils">
        <h2>Account Details</h2>
        <p id="{{user.id}}">Username: {{user}}</p>
        <p>Name: {{user.first_name}}</p>
        {% if not user.is_registered %}<h3>Your are still not registered!!!<br/> don't miss this chance of beign a part of ACM Nexus!! </h3> {% endif %}
        {% if user.is_registered %} <h3>Congrats!!! You are registered for the event!! </h3>{% endif %}
    </div>
            <div class="buttons">
                <div class="button-container">
                <a onclick="openBlock()" style="color: black;">Change Password</a>
        <a href="{% url 'MainApp:logout' %}" style="color: black;">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <canvas id="nexusCanvas"></canvas>
    <script >
        const canvas = document.getElementById('nexusCanvas');
    const ctx = canvas.getContext('2d');
    
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    
    let particles = [];
    const particleCount = 100;
    
    class Particle {
        constructor() {
            this.x = Math.random() * canvas.width;
            this.y = Math.random() * canvas.height;
            this.size = Math.random() * 3 + 1;
            this.speedX = (Math.random() - 0.5) * 0.3;
            this.speedY = (Math.random() - 0.5) * 0.3;
            this.color = `rgba(173, 216, 230, 1)`;
        }
    
        update() {
            this.x += this.speedX;
            this.y += this.speedY;
    
            if (this.x > canvas.width || this.x < 0) this.speedX *= -1;
            if (this.y > canvas.height || this.y < 0) this.speedY *= -1;
        }
    
        draw() {
            ctx.beginPath();
            ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
            ctx.fillStyle = this.color;
            ctx.fill();
        }
    }
    
    function createParticles() {
        particles = [];
        for (let i = 0; i < particleCount; i++) {
            particles.push(new Particle());
        }
    }
    
    function drawConnections() {
        for (let i = 0; i < particles.length; i++) {
            for (let j = i + 1; j < particles.length; j++) {
                let dx = particles[i].x - particles[j].x;
                let dy = particles[i].y - particles[j].y;
                let distance = Math.sqrt(dx * dx + dy * dy);
    
                if (distance < 120) {
                    ctx.beginPath();
                    ctx.strokeStyle = `rgba(173, 216, 230, ${1 - distance / 120})`;
                    ctx.lineWidth = 0.5;
                    ctx.moveTo(particles[i].x, particles[i].y);
                    ctx.lineTo(particles[j].x, particles[j].y);
                    ctx.stroke();
                }
            }
        }
    }
    
    function animate() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
    
        particles.forEach(particle => {
            particle.update();
            particle.draw();
        });
    
        drawConnections();
        requestAnimationFrame(animate);
    }
    
    window.addEventListener('resize', () => {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        createParticles();
    });
    
    createParticles();
    animate();
    </script>
    {% endblock body %}
    {% block script %}
        <script type="text/javascript" src="{% static '/MainApp/account.js' %}"></script>
    {% endblock script %}

MainApp/templates/MainApp/confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/recovery.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{% endblock head %}
{% block body %}
    <div class="inner-container">
        <span class="material-symbols-outlined">
            check
            </span>
        <div class="text">You will receive mail in your provided mail id in a while.</div>
    </div>
{% endblock body %}

MainApp/templates/MainApp/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title> Login and Registration Form </title>
    <link rel="stylesheet" href="{% static 'MainApp/login.css'%}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

{% endblock head %}

{% block body %}
  <div class="conatiner-inner">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static 'Images/frontImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">ACM Nexus</span>
          <span class="text-2">Unite Through Innovation</span>
        </div>
      </div>
      <div class="back">
        <img class="backImg" src="{% static 'Images/backImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">ACM Nexus</span>
          <span class="text-2">Unite Through Innovation</span>
        </div>
      </div>
    </div>
    <div class="forms">
        <div class="form-content">
          <div class="login-form">
            <div class="title">Login</div>
            {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" placeholder="Enter your email" id="email" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" id='password' placeholder="Enter your password" required>
              </div>
              <div class="text"><a href="{% url 'MainApp:recovery' %}">Forgot password?</a></div>
              <div class="button input-box">
                <input type="submit" value="Submit" onclick="login()">
              </div>
              <div class="text sign-up-text">Don't have an account? <label for="flip">Signup now</label></div>
            </div>
      </div>
        <div class="signup-form">
          <div class="title">Signup</div>
        <form action="{% url 'MainApp:register' %}" onsubmit="return validateForm()" method="post">
          {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" id="name" name="name" placeholder="Enter your name" required>
              </div>
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" id="USN" name="USN" placeholder="Enter your USN" required>
              </div>
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="number" id="year" name="year" placeholder="Year of Graduation:" required>
              </div>
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" id='' name="email" placeholder="Enter your email" required>
              </div>

              <div class="button input-box">
                <input type="submit" value="Submit">
              </div>
              <div class="text sign-up-text">Already have an account? <label for="flip">Login now</label></div>
            </div>
      </form>
    </div>
    </div>
    </div>
  </div>
{% endblock body %}
{% block script %}<script type="text/javascript" src="{% static '/MainApp/login.js' %}"></script>

<canvas id="nexusCanvas"></canvas>
<script >
    const canvas = document.getElementById('nexusCanvas');
const ctx = canvas.getContext('2d');

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let particles = [];
const particleCount = 100;

class Particle {
  constructor() {
        this.x = Math.random() * canvas.width;
        this.y = Math.random() * canvas.height;
        this.size = Math.random() * 3 + 1;
        this.speedX = (Math.random() - 0.5) * 0.3;
        this.speedY = (Math.random() - 0.5) * 0.3;
        this.color = `rgba(173, 216, 230, 0.5)`;
    }

    update() {
        this.x += this.speedX;
        this.y += this.speedY;

        if (this.x > canvas.width || this.x < 0) this.speedX *= -1;
        if (this.y > canvas.height || this.y < 0) this.speedY *= -1;
    }

    draw() {
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
        ctx.fillStyle = this.color;
        ctx.fill();
    }
}

function createParticles() {
    particles = [];
    for (let i = 0; i < particleCount; i++) {
        particles.push(new Particle());
    }
}

function drawConnections() {
    for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
            let dx = particles[i].x - particles[j].x;
            let dy = particles[i].y - particles[j].y;
            let distance = Math.sqrt(dx * dx + dy * dy);

            if (distance < 120) {
                ctx.beginPath();
                ctx.strokeStyle = `rgba(173, 216, 230, ${1 - distance / 120})`;
                ctx.lineWidth = 0.5;
                ctx.moveTo(particles[i].x, particles[i].y);
                ctx.lineTo(particles[j].x, particles[j].y);
                ctx.stroke();
            }
        }
    }
}

function animate() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    particles.forEach(particle => {
        particle.update();
        particle.draw();
    });

    drawConnections();
    requestAnimationFrame(animate);
}

window.addEventListener('resize', () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    createParticles();
});

createParticles();
animate();
</script>
{% endblock script %}

MainApp/templates/MainApp/recovery.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'MainApp/recovery.css' %}">
{% endblock head %}
{% block body %}
    <form class="inner-container" method="post" action="{% url 'MainApp:sendpassword' %}">
        {% csrf_token %}
        <label for="email" class="label-email">Enter registered mail id </label><input id="email" name="email" type="email" placeholder="Email id" required>
        <input type="submit" class="submit">
    </form>
{% endblock body %}